Define hostname    jellyfin  
Define server_fqdn ${hostname}.${domain}
Define proxy_to    http://127.0.0.1:8096/

<VirtualHost ${server_fqdn}:80>
  ServerSignature Off
  ServerName      ${server_fqdn}
  ServerAlias     ${server_fqdn}
  ServerAdmin     ${admin_email}

  KeepAlive off
  TimeOut   3

  LogLevel     warn
  ErrorLog     /share/Configuration/apache/log/${hostname}/errors.log
  CustomLog    /share/Configuration/apache/log/${hostname}/common.log common

  # Use an empty document root
  DocumentRoot /usr/local/AppCentral/cappysan-apache/htdocs
  <Directory /usr/local/AppCentral/cappysan-apache/htdocs>
    Options FollowSymlinks
    AllowOverride None
    Require all denied
  </Directory>

  ProxyPass        / ${proxy_to}
  ProxyPassReverse / ${proxy_to}
</VirtualHost>
# vim: ft=apache
