# Used by prometheus-apache-exporter
#
<IfModule mod_status.c>
<VirtualHost localhost:80>
  ServerSignature off
  LogLevel        warn
  KeepAlive       off
  TimeOut         3

  <Directory /usr/local/AppCentral/cappysan-apache/htdocs>
    Options FollowSymlinks
    AllowOverride None
    Require all denied
  </Directory>

  <Location /server-status>
    SetHandler server-status
    Require local granted
  </Location>

  <IfModule mod_proxy.c>
    ProxyStatus On
  </IfModule>

</VirtualHost>
</IfModule>
# vim: ft=apache
