# Used by prometheus-apache-exporter
#
# Available as http://localhost/server-status from localhost only
#
<IfModule mod_status.c>
<VirtualHost localhost:80 127.0.0.1:80>
  ServerSignature off
  LogLevel        warn
  KeepAlive       off
  TimeOut         3

  <Location /server-status>
    SetHandler server-status
    Require local granted
  </Location>

  <IfModule mod_proxy.c>
    ProxyStatus On
  </IfModule>

</VirtualHost>
</IfModule>
# vim: ft=apache
