# SPDX-License-Identifier: MIT
#
---
# The following file enables recreating a templated output dir by executing:
#   mk-scaffold clone "https://gitlab.com/cappysan/scaffolds/asustor-template" --input-file .answers.yml --output-dir output
answers:
  - include: "~/.config/scaffold/answers.yml"
    optional: True

  - author: "Julien Lecomte"
  - email: "julien@cappysan.dev"

  - project_name: "cappysan-apache"
  - project_slug: "cappysan-apache"
  - project_url: "https://gitlab.com/cappysan/asustor/apache"
  - project_description: "Apache2 web server."

  - has_documentation: False
  - documentation_url: ""

  - has_ci: True
  - has_pages: False
  - has_releases: True

  - has_precommit: True
  - has_precommit_codespell: True
  - has_precommit_nitpick: True

  - license: "MIT"
  - version: "2.4.62-r97"
  - version_style: "semver-rev"
  - copyright_string: "Cappysan, Julien Lecomte, and contributors"

  - keep_placeholders: False

  - template_url: "https://gitlab.com/cappysan/scaffolds/asustor-template"
  - template_version: "1.1.0-r4"

  - creation_year: "2025"
  - last_update: "2026-06-15 17:53:50"

  - maintainer: "Cappysan"
  - developer: "Cappysan"

  - app_name: "Apache"
  - cfg_name: "apache"
  - cappysan_name: "cappysan-apache"
  - asustor_name: "asustor-apache"

  - apk_description: "Leverage the full power of Apache2 web server."
  - has_adm_desktop: True

  # Items without visible questions:
  - depends: '"python3(>=3.10.0)","httpd-2.4.43"'
  - adm_desktop_customizable: False
  - boot_priority_start: 70
  - boot_priority_stop: 30
  - has_upstream: True
