/* _AS_STRINGS */
_AS_STRINGS = {};

/*APACHE*/
_AS_STRINGS.APACHE = {};
_AS_STRINGS.APACHE.APP_TITLE            = 'Apache';
_AS_STRINGS.APACHE.TAB_SETTINGS         = 'Settings';
_AS_STRINGS.APACHE.TAB_SITES            = 'Sites';
_AS_STRINGS.APACHE.SECTION_SERVER       = 'Server';
_AS_STRINGS.APACHE.SECTION_SITES        = 'Sites Available';
_AS_STRINGS.APACHE.SECTION_SITE_CONTENT = 'Configuration';
_AS_STRINGS.APACHE.LABEL_SERVER_NAME    = 'Server Name';
_AS_STRINGS.APACHE.LABEL_DOMAIN         = 'Domain';
_AS_STRINGS.APACHE.LABEL_ADMIN_EMAIL    = 'Admin Email';
_AS_STRINGS.APACHE.COL_SITE_NAME        = 'Name';
_AS_STRINGS.APACHE.COL_SITE_STATUS      = 'Status';
_AS_STRINGS.APACHE.STATUS_ENABLED       = 'Enabled';
_AS_STRINGS.APACHE.STATUS_DISABLED      = 'Disabled';
_AS_STRINGS.APACHE.BTN_ENABLE           = 'Enable';
_AS_STRINGS.APACHE.BTN_DISABLE          = 'Disable';
