/* _AS_STRINGS */
_AS_STRINGS = {};

/*APACHE*/
_AS_STRINGS.APACHE = {};
_AS_STRINGS.APACHE.APP_TITLE            = 'Apache';
_AS_STRINGS.APACHE.TAB_SETTINGS         = 'Settings';
_AS_STRINGS.APACHE.TAB_SITES            = 'Sites';
_AS_STRINGS.APACHE.SECTION_SERVER       = 'Server';
_AS_STRINGS.APACHE.SECTION_LINK         = 'Link';
_AS_STRINGS.APACHE.LINK_OPEN            = 'Open NAS interface';
_AS_STRINGS.APACHE.LINK_OVERRIDE_HINT   = 'Custom URL override';
_AS_STRINGS.APACHE.SECTION_SITES        = 'Sites Available';
_AS_STRINGS.APACHE.SECTION_SITE_CONTENT = 'Configuration';
_AS_STRINGS.APACHE.LABEL_SERVER_NAME    = 'Server FQDN';
_AS_STRINGS.APACHE.LABEL_DOMAIN         = 'Domain';
_AS_STRINGS.APACHE.LABEL_ADMIN_EMAIL    = 'Admin Email';
_AS_STRINGS.APACHE.COL_SITE_NAME        = 'Name';
_AS_STRINGS.APACHE.COL_SITE_STATUS      = 'Status';
_AS_STRINGS.APACHE.STATUS_ENABLED       = 'Enabled';
_AS_STRINGS.APACHE.STATUS_DISABLED      = 'Disabled';
_AS_STRINGS.APACHE.BTN_ENABLE           = 'Enable';
_AS_STRINGS.APACHE.BTN_DISABLE          = 'Disable';
_AS_STRINGS.APACHE.TAB_DEFAULT              = '_default_';
_AS_STRINGS.APACHE.SECTION_APACHE_SETTINGS  = 'Settings';
_AS_STRINGS.APACHE.LABEL_APACHE_HOSTNAME    = 'Hostname';
_AS_STRINGS.APACHE.LABEL_APACHE_FQDN        = 'Server FQDN';
_AS_STRINGS.APACHE.LABEL_APACHE_PLACEHOLDERS = 'Available placeholders: ${hostname}, ${domain}';
_AS_STRINGS.APACHE.LABEL_APACHE_REDIRECT    = 'HTTP redirection';
_AS_STRINGS.APACHE.LABEL_APACHE_PROXY_TO    = 'HTTPS proxy';
_AS_STRINGS.APACHE.BTN_RESTART          = 'Restart';
_AS_STRINGS.APACHE.BTN_RELOAD           = 'Reload';
