# Configuration for `nas.example.com`
#
# Default redirect to SSL version
#
Define hostname    nas
Define server_fqdn ${hostname}.${domain}
Define redirect_to https://${server_fqdn}/

# HTTPS proxy:
Define proxy_to    https://127.0.0.1:8001/

<VirtualHost _default_:80>
  ServerSignature Off
  ServerName      ${server_fqdn}
  ServerAlias     ${server_fqdn}
  ServerAdmin     ${admin_email}

  KeepAlive off
  TimeOut   3

  LogLevel     warn
  ErrorLog     /share/Configuration/apache/logs/default-errors.log
  CustomLog    /share/Configuration/apache/logs/default-common.log common

  # Use an empty document root
  DocumentRoot /usr/local/AppCentral/cappysan-apache/htdocs
  <Directory /usr/local/AppCentral/cappysan-apache/htdocs>
    Options FollowSymlinks
    AllowOverride None
    Require all denied
  </Directory>

  Redirect permanent / ${redirect_to}
</VirtualHost>


<VirtualHost _default_:443>
  ServerSignature Off
  ServerName      ${server_fqdn}
  ServerAlias     ${server_fqdn}
  ServerAdmin     ${admin_email}

  LogLevel     warn
  ErrorLog     /share/Configuration/apache/logs/default-errors.log
  CustomLog    /share/Configuration/apache/logs/default-common.log common

  SSLEngine         On
  SSLProxyEngine    On
  ProxyPreserveHost On
  SSLProxyVerify    Off

  SSLProtocol -all +TLSv1.2 +TLSv1.3
  AllowEncodedSlashes NoDecode
  RequestHeader set X-Forwarded-Proto "https"

  SSLCertificateKeyFile /usr/builtin/etc/certificate/ssl.key
  SSLCertificateFile    /usr/builtin/etc/certificate/ssl.pem

  # https://mozilla.github.io/server-side-tls/ssl-config-generator/
  Header always set Strict-Transport-Security "max-age=86400"

  # Use an empty document root
  DocumentRoot /usr/local/AppCentral/cappysan-apache/htdocs
  <Directory /usr/local/AppCentral/cappysan-apache/htdocs>
    Options FollowSymlinks
    AllowOverride None
    Require all denied
  </Directory>

  ProxyPass        / ${proxy_to}
  ProxyPassReverse / ${proxy_to}
</VirtualHost>

<VirtualHost ${server_fqdn}:80>
  ServerSignature Off
  ServerName      ${server_fqdn}
  ServerAlias     ${server_fqdn}
  ServerAdmin     ${admin_email}

  KeepAlive off
  TimeOut   3

  LogLevel     warn
  ErrorLog     /share/Configuration/apache/logs/default-errors.log
  CustomLog    /share/Configuration/apache/logs/default-common.log common

  # Use an empty document root
  DocumentRoot /usr/local/AppCentral/cappysan-apache/htdocs
  <Directory /usr/local/AppCentral/cappysan-apache/htdocs>
    Options FollowSymlinks
    AllowOverride None
    Require all denied
  </Directory>

  Redirect permanent / ${redirect_to}
</VirtualHost>


<VirtualHost ${server_fqdn}:443>
  ServerSignature Off
  ServerName      ${server_fqdn}
  ServerAlias     ${server_fqdn}
  ServerAdmin     ${admin_email}

  LogLevel     warn
  ErrorLog     /share/Configuration/apache/logs/default-errors.log
  CustomLog    /share/Configuration/apache/logs/default-common.log common

  SSLEngine         On
  SSLProxyEngine    On
  ProxyPreserveHost On
  SSLProxyVerify    Off

  SSLProtocol -all +TLSv1.2 +TLSv1.3
  AllowEncodedSlashes NoDecode
  RequestHeader set X-Forwarded-Proto "https"

  SSLCertificateKeyFile /usr/builtin/etc/certificate/ssl.key
  SSLCertificateFile    /usr/builtin/etc/certificate/ssl.pem

  # https://mozilla.github.io/server-side-tls/ssl-config-generator/
  Header always set Strict-Transport-Security "max-age=86400"

  # Use an empty document root
  DocumentRoot /usr/local/AppCentral/cappysan-apache/htdocs
  <Directory /usr/local/AppCentral/cappysan-apache/htdocs>
    Options FollowSymlinks
    AllowOverride None
    Require all denied
  </Directory>

  ProxyPass        / ${proxy_to}
  ProxyPassReverse / ${proxy_to}
</VirtualHost>
# vim: ft=apache
