#!/usr/bin/env sh

WHAT=apache

. /usr/local/AppCentral/cappysan-apache/.env.install

function logger() {
  echo "${@}" >&2
  syslog --log 0 --level 0 --user SYSTEM --event "${@}"
}

if test -f ${APKG_CFG_DIR}/active; then
  if test -e /var/run/apache/apache.pid; then
    logger "[Certbot] Restarting ${WHAT}..."
    ${APKG_PKG_DIR}/CONTROL/start-stop.sh reload
  fi
fi
exit 0
