#!/usr/bin/env sh

WHAT=apache

. /usr/local/AppCentral/cappysan-apache/.env.install

function logger() {
  echo "${@}" >&2
  syslog --log 0 --level 0 --user SYSTEM --event "${@}"
}

if test -e /var/run/apache/apache.pid; then
  ${APKG_PKG_DIR}/CONTROL/start-stop.sh reload
fi
exit 0
